### PR TITLE
Add how to withdraw from yEarn and yVaults guide

### PR DESCRIPTION
**Pull request by juafrapat**
Solves #86. Added estimated gas cost of withdrawing from any yVault with the current strategies.

### CODE REVIEW

**Comment by lehnberg** [comment]
@juafrapat thank you for the PR! I have some changes I'd like to commit to your pull request, but I am unable to push to your fork. Can you please ensure that you have "Allow edits from maintainers" checkbox is checked?

For more info, please see here:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Review by lehnberg — CHANGES_REQUESTED** [review]
See comment in PR

**Comment by juafrapat** [comment]
> @juafrapat thank you for the PR! I have some changes I'd like to commit to your pull request, but I am unable to push to your fork. Can you please ensure that you have "Allow edits from maintainers" checkbox is checked?
> 
> For more info, please see here:
> https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

Weird, the box is checked. 
Screenshot from 2020-11-25 20-03-46

**Comment by lehnberg** [comment]
Hmm weird indeed. It could be due to the fact that you're PRing in from your master branch, perhaps it's not possible for me to push to your master?

How about you open a new PR from a clean branch of your own fork, please follow steps here:
https://gist.github.com/Chaser324/ce0505fbed06b947d962

I should then be able to commit changes to that and merge :+1:

**Pull request closed without merging**
